/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC20__factory } from "./ERC20__factory";
export { GLDToken__factory } from "./GLDToken__factory";
export { IERC20__factory } from "./IERC20__factory";
export { IERC20Metadata__factory } from "./IERC20Metadata__factory";
